# Generated by Django 6.0.6 on 2026-07-26 14:30

from django.db import migrations

INITIAL_CATEGORIES = [
    "Music",
    "Technology",
    "Sports",
    "Arts & Culture",
    "Food & Drink",
    "Business",
    "Education",
    "Health & Wellness",
    "Travel & Outdoor",
    "Gaming",
]


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model("events", "Category")
    for name in INITIAL_CATEGORIES:
        Category.objects.get_or_create(name=name)


def remove_initial_categories(apps, schema_editor):
    Category = apps.get_model("events", "Category")
    Category.objects.filter(name__in=INITIAL_CATEGORIES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]
